import tkinter as tk
window=tk.Tk()
window.geometry("202x550")
def onclick():
    print(1)
btn1=tk.Button(text="ЗАЛ", command=onclick)
btn1.grid(row=0, column=0)
chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="выбор лампочки", variable=chkvar1, onvalue=1, offvalue=0)
chkbtn1.grid(row=1, column=0)
scl1=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl1.grid(row=2, column=0)
btn2=tk.Button(text="СПАЛЬНЯ №1", command=onclick)
btn2.grid(row=3, column=0)
chkvar2=tk.IntVar()
chkbtn2=tk.Checkbutton(text="выбор лампочки", variable=chkvar2, onvalue=1, offvalue=0)
chkbtn2.grid(row=4, column=0)
scl2=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl2.grid(row=5, column=0)
btn3=tk.Button(text="СПАЛЬНЯ №2", command=onclick)
btn3.grid(row=6, column=0)
chkvar3=tk.IntVar()
chkbtn3=tk.Checkbutton(text="выбор лампочки", variable=chkvar3, onvalue=1, offvalue=0)
chkbtn3.grid(row=7, column=0)
scl3=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl3.grid(row=8, column=0)
btn4=tk.Button(text="КУХНЯ", command=onclick)
btn4.grid(row=9, column=0)
chkvar4=tk.IntVar()
chkbtn4=tk.Checkbutton(text="выбор лампочки", variable=chkvar4, onvalue=1, offvalue=0)
chkbtn4.grid(row=10, column=0)
scl4=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl4.grid(row=11, column=0)
btn5=tk.Button(text="ВАННАЯ", command=onclick)
btn5.grid(row=12, column=0)
chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="выбор лампочки", variable=chkvar1, onvalue=1, offvalue=0)
chkbtn1.grid(row=13, column=0)
scl1=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl1.grid(row=14, column=0)
btn5=tk.Button(text="КОРИДОР", command=onclick)
btn5.grid(row=12, column=0)
chkvar1=tk.IntVar()
chkbtn1=tk.Checkbutton(text="выбор лампочки", variable=chkvar1, onvalue=1, offvalue=0)
chkbtn1.grid(row=13, column=0)
scl1=tk.Scale(label="яркость", from_=1, to=100, orient=tk.HORIZONTAL, length=200, width=10)
scl1.grid(row=14, column=0)
window.mainloop()